In [1]:
import pandas as pd
import numpy as np

genotype = pd.read_csv("genotype_train_filled.csv")
genotype.drop(["Unnamed: 0"], axis = 1, inplace = True)
genotype

,PatientId,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_368,SNP_369,SNP_370,SNP_371,SNP_372,SNP_373,SNP_374,SNP_375,SNP_376,SNP_377
0,1883,0.0,-1.0,-1,-1.0,0.0,-1.0,-1.0,0.0,0.0,...,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0
1,530,0.0,-1.0,0,0.0,0.0,-1.0,-1.0,0.0,0.0,...,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0
2,1802,0.0,-1.0,0,0.0,-1.0,0.0,0.0,-1.0,-1.0,...,-1.0,0.0,0.0,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0
3,1110,0.0,-1.0,0,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,1.0,0.0
4,1971,-1.0,0.0,-1,-1.0,0.0,0.0,-1.0,0.0,-1.0,...,-1.0,0.0,0.0,1.0,-1.0,-1.0,0.0,-1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,276,-1.0,1.0,-1,-1.0,1.0,0.0,-1.0,1.0,0.0,...,-1.0,0.0,0.0,1.0,-1.0,-1.0,0.0,1.0,0.0,0.0
1986,758,-1.0,-1.0,0,-1.0,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,-1.0
1987,1870,-1.0,0.0,-1,0.0,0.0,-1.0,-1.0,0.0,1.0,...,-1.0,0.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0
1988,257,-1.0,-1.0,-1,0.0,0.0,-1.0,-1.0,-1.0,0.0,...,1.0,0.0,-1.0,0.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0
1989,971,0.0,0.0,0,0.0,0.0,-1.0,0.0,0.0,0.0,...,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,0.0,1.0,0.0

In [2]:
genotype.isnull().describe()

,PatientId,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_368,SNP_369,SNP_370,SNP_371,SNP_372,SNP_373,SNP_374,SNP_375,SNP_376,SNP_377
count,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,...,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990
unique,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,...,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990

# No missing values, life's good, but we still have to merge on ID

In [3]:
from sklearn.model_selection import train_o

### doing merging

In [4]:
df = genotype.copy()
df

,PatientId,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_368,SNP_369,SNP_370,SNP_371,SNP_372,SNP_373,SNP_374,SNP_375,SNP_376,SNP_377
0,1883,0.0,-1.0,-1,-1.0,0.0,-1.0,-1.0,0.0,0.0,...,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0
1,530,0.0,-1.0,0,0.0,0.0,-1.0,-1.0,0.0,0.0,...,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0
2,1802,0.0,-1.0,0,0.0,-1.0,0.0,0.0,-1.0,-1.0,...,-1.0,0.0,0.0,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0
3,1110,0.0,-1.0,0,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,1.0,0.0
4,1971,-1.0,0.0,-1,-1.0,0.0,0.0,-1.0,0.0,-1.0,...,-1.0,0.0,0.0,1.0,-1.0,-1.0,0.0,-1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,276,-1.0,1.0,-1,-1.0,1.0,0.0,-1.0,1.0,0.0,...,-1.0,0.0,0.0,1.0,-1.0,-1.0,0.0,1.0,0.0,0.0
1986,758,-1.0,-1.0,0,-1.0,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,-1.0
1987,1870,-1.0,0.0,-1,0.0,0.0,-1.0,-1.0,0.0,1.0,...,-1.0,0.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0
1988,257,-1.0,-1.0,-1,0.0,0.0,-1.0,-1.0,-1.0,0.0,...,1.0,0.0,-1.0,0.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0
1989,971,0.0,0.0,0,0.0,0.0,-1.0,0.0,0.0,0.0,...,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,0.0,1.0,0.0

In [5]:
initDF = pd.read_csv("Clinical_Data.train.txt", sep = "\t")
initDF

,PatientId,Gender,Height,Weight,Diag,AgeAtDiag,SmokeAtDiag,Leu,Hb,CRP,ESR,Fer,B12,Fol,Alk,Alb
0,1,2,165.0,59.0,CD,16.0,0,5.5,120.0,20,NaN,NaN,NaN,NaN,61.0,NaN
1,3,2,NaN,NaN,UC,31.0,0,7.6,134.0,5,8.0,53,NaN,NaN,43.0,NaN
2,4,1,174.0,67.0,CD,31.0,0,NaN,103.0,40,NaN,226,299,7.9,69.0,35.0
3,5,2,172.0,60.0,UC,56.0,1,13.6,104.0,23,26.0,NaN,NaN,NaN,87.0,32.0
4,6,1,182.0,74.0,CD,22.0,1,5.7,150.0,2,NaN,NaN,NaN,NaN,NaN,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,2026,1,175.0,72.0,CD,25.0,1,6.3,153.0,2.3,NaN,33,258,NaN,52.0,42.0
1986,2027,1,182.0,77.0,CD,26.0,-1,9.9,166.0,NaN,NaN,NaN,NaN,NaN,36.0,NaN
1987,2028,1,170.0,68.0,CD,22.0,0,4.3,115.0,2,10.0,24,161,8.8,45.0,NaN
1988,2029,1,NaN,NaN,CD,16.0,-1,10.3,143.0,15,NaN,49,NaN,NaN,NaN,37.0
1989,2030,1,176.0,80.0,UC,36.0,0,11.2,145.0,4,NaN,NaN,NaN,NaN,44.0,NaN

In [ ]:
# found an easy way to align IDs and check correctness

df = df.sort_values("PatientId")
df.index = np.arange(0, len(df))
(df['PatientId'] == initDF['PatientId']).describe()

Adding the diagnosis column

In [ ]:
df["Diag"] = initDF["Diag"]
df

dropping IDs

In [ ]:
ids = df['PatientId']
df.drop('PatientId', axis=1, inplace=True)

replacing strings with simply values

In [ ]:
df.replace(to_replace="CD", value = 1, inplace=True )
df.replace(to_replace="UC", value = 2, inplace=True )
df

### sampling a holdoutDF for independent testing

In [ ]:
n_random_samples = int(np.ceil(len(df)/20))
holdoutDF = df.sample(n_random_samples)
df.drop(holdoutDF.index, axis=0, inplace=True)

holdoutDF

## Starting the ML part

In [ ]:
target = 'Diag'

X = df.drop([target], axis=1)
y = df[[target]]

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0)

In [ ]:
# a function for rapid f1score prediction

scores = []

def get_f1_score(model):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    res = f1_score(y_test, preds, average="weighted")
    scores.append(res)
    
def clean_scores():
    scores.clear()

In [ ]:
# importing all the models we will be using

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

### A simple try to see models' performance on default parameters

In [ ]:
# defining our models
RF = RandomForestClassifier()
LR = LogisticRegression()
KNN = KNeighborsClassifier()
SVM = SVC(C=0.0001)
DT = DecisionTreeClassifier()
BGDT = BaggingClassifier(DecisionTreeClassifier())
ADB = AdaBoostClassifier(DecisionTreeClassifier())
GBD = GradientBoostingClassifier()
EVCh = VotingClassifier(estimators=[('lr',LR),('rf',RF),('svm',SVM), ("gbd", GBD),("adb",ADB), 
                                  ("dt",DT), ("bgdt", BGDT)],voting='hard')
EVCs = VotingClassifier(estimators=[('lr',LR),('rf',RF), ("gbd", GBD),("adb",ADB), 
                                  ("dt",DT), ("bgdt", BGDT)],voting='soft')

models = [LR, KNN, SVM, DT, ADB , RF, BGDT, EVCh, EVCs, GBD]

In [ ]:
for model in models:
    get_f1_score(model)

In [ ]:
scores

### testing the holdout

In [ ]:
holdoutDF

In [ ]:
X_holdout = holdoutDF.drop([target], axis=1)
y_holdout = holdoutDF[[target]]

In [ ]:
model

In [ ]:
predsHoldout = model.predict(X_holdout)
resHoldout = f1_score(y_holdout, predsHoldout, average = "weighted")
print(resHoldout)

### Some exploring, trying to bet better results with as little work as possible

In [ ]:
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
import numpy as np

In [ ]:
# RF

n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']

gridRF = dict(n_estimators=n_estimators,max_features=max_features)
cvRF = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_searchRF = GridSearchCV(estimator=RF, param_grid=gridRF, n_jobs=-1, cv=cvRF, scoring='accuracy',error_score=0)
grid_searchRF.fit(X_train, np.ravel(y_train,order='C'))
best_modelRF = grid_searchRF.best_estimator_

predsRF = best_modelRF.predict(X_test)

resRF = f1_score(y_test, predsRF, average = "weighted")

resRF

In [ ]:
# LR

LRt = LogisticRegression()

solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01, 0.001]

gridLRt = dict(solver=solvers,penalty=penalty,C=c_values)
cvLRt = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_searchLRt = GridSearchCV(estimator=LRt, param_grid=gridLRt, n_jobs=-1, cv=cvLRt)
grid_searchLRt.fit(X_train, np.ravel(y_train,order='C'))
best_modelLRt = grid_searchLRt.best_estimator_

predsLRt = best_modelLRt.predict(X_test)

resLRt = f1_score(y_test, predsLRt, average = "weighted")

resLRt

In [ ]:
# KRR

from sklearn.linear_model import RidgeClassifier

RC = RidgeClassifier()
alpha = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

gridRC = dict(alpha = alpha)
cvRC = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_searchRC = GridSearchCV(estimator=RC, param_grid=gridRC, n_jobs=-1, cv=cvRC)
grid_searchRC.fit(X_train, np.ravel(y_train,order='C'))
best_modelRC = grid_searchRC.best_estimator_

predsRC = best_modelRC.predict(X_test)

resRC = f1_score(y_test, predsRC, average = "weighted")

resRC

In [ ]:
# Training a KNN

KNNt = KNeighborsClassifier()
n_neighbors = range(1, 21, 2)
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']

gridKNNt = dict(n_neighbors = n_neighbors,weights = weights, metric = metric)
cvKNNt = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_searchKNNt = GridSearchCV(estimator=KNNt, param_grid=gridKNNt, n_jobs=-1, cv=cvKNNt)
grid_searchKNNt.fit(X_train, np.ravel(y_train,order='C'))
best_modelKNNt = grid_searchKNNt.best_estimator_

predsKNNt = best_modelKNNt.predict(X_test)

resKNNt = f1_score(y_test, predsKNNt, average = "weighted")

resKNNt

# Big boy ML time
### if you don't know what to do, use decision trees

I'll do good-ol grid search to find best hyperparams

In [ ]:
param_grid = {
    "n_estimators": [10, 100, 120, 140, 150],
    "max_depth": [3, 7, 9],
}

In [ ]:
gridSearchModels = [RF, GBD]

for model in gridSearchModels:

    grid_search = GridSearchCV(model, param_grid, cv=5)
    grid_search.fit(X_train, y_train)
    best_model = grid_search.best_estimator_
    
    preds = best_model.predict(X_test)
    res = f1_score(y_test, preds, average = "weighted")
    print(res)

    print(f"Best Hyperparameters for {model}: {grid_search.best_params_}")

In [ ]:
predsBMhold = best_model.predict(X_holdout)
resBMhold = f1_score(y_holdout, predsBMhold, average = "weighted")
resBMhold